logging:
  path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}

server:
  port: ${PORT:5002}
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME:jalgo-arena-problems-pg}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
